apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam2ip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cam2ip
  template:
    metadata:
      labels:
        app: cam2ip
    spec:
      containers:
        - name: cam2ip
          image: gen2brain/cam2ip
          ports:
            - containerPort: 56000
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/video0
              name: dev-video0
      volumes:
        - name: dev-video0
          hostPath:
            path: /dev/video0
           # type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: cam2ip-service
spec:
  selector:
    app: cam2ip
  ports:
    - protocol: TCP
      port: 56000
      targetPort: 56000
  type: NodePort
